trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
    steps:
    - checkout: self
    - task: LambdaNETCoreDeploy@1
      inputs:
        awsCredentials: 'AWS-Connection'
        regionName: 'us-west-1'
        command: 'deployFunction'
        packageOnly: false
        lambdaProjectPath: '$(Build.SourcesDirectory)/Project4.sln'
        functionName: 'MasterPeaceAppLambda'
        functionHandler: 'Project4.Api::FunctionHandlerAsync'
        functionMemory: 512
        functionTimeout: 30

