trigger:
- develop

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
    steps:
    - checkout: self
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    - task: LambdaNETCoreDeploy@1
      inputs:
        awsCredentials: 'AWS-Connection'
        regionName: 'us-west-1'
        command: 'deployFunction'
        functionName: 'MasterPeaceAppLambda'
        functionHandler: 'Project4.Api::FunctionHandlerAsync'
        functionMemory: 512
        functionTimeout: 30
        
