trigger:
- develop

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
  buildConfiguration: 'Release'
  buildPlatform: 'Any CPU'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      name: 'Default'
    steps:
    - checkout: self

    - task: UseDotNet@2
      displayName: 'Instalar .NET SDK'
      inputs:
        packageType: 'sdk'
        version: '8.0.303'
        installationPath: $(Agent.ToolsDirectory)/dotnet
    
    - task: UseDotNet@2
      displayName: 'Instalar .NET Runtime'
      inputs:
        packageType: 'runtime'
        version: '8.0.7'
        installationPath: $(Agent.ToolsDirectory)/dotnet

    - task: NuGetCommand@2
      displayName: 'Restaurar Paquetes NuGet'
      inputs:
        restoreSolution: '**/*.sln'
    
    - task: DotNetCoreCLI@2
      displayName: 'Compilar Solución'
      inputs:
        command: 'build'
        projects: '**/*.sln'
        arguments: '--configuration $(buildConfiguration) --no-restore'

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)

    - publish: $(System.DefaultWorkingDirectory)/bin/$(buildConfiguration)/
      artifact: drop
      displayName: 'Publicar Artefactos'
